<?php
session_start();
if (!isset($_SESSION['user_id'])) { 
    header("Location: ../index.php"); 
    exit; 
}
require_once '../includes/db.php';

$owners = $pdo->query("SELECT id, name FROM owners ORDER BY name ASC")->fetchAll();
$msg = "";

if (empty($_SESSION['csrf_token'])) {
    $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
}

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    if (!isset($_POST['csrf_token']) || $_POST['csrf_token'] !== $_SESSION['csrf_token']) {
        die("Security Exception: Illegal token state verification mismatch.");
    }

    // High fidelity autogenerated hex tracking parameters for RFID tag structure
    $animal_id = "RFID-" . rand(100, 999) . "-" . strtoupper(substr(md5(uniqid()), 0, 4)); 
    $owner_id   = filter_input(INPUT_POST, 'owner_id', FILTER_VALIDATE_INT);
    $species    = $_POST['species'] ?? '';
    $breed      = filter_input(INPUT_POST, 'breed', FILTER_SANITIZE_SPECIAL_CHARS);
    $age_months = filter_input(INPUT_POST, 'age_months', FILTER_VALIDATE_INT) ?: 0;
    $gender     = $_POST['gender'] ?? 'Male';

    if (!empty($owner_id) && !empty($species)) {
        try {
            $stmt = $pdo->prepare("INSERT INTO animals (animal_id, owner_id, species, breed, age_months, gender, status) VALUES (?, ?, ?, ?, ?, ?, 'Healthy')");
            $stmt->execute([$animal_id, $owner_id, $species, $breed, $age_months, $gender]);
            
            unset($_SESSION['csrf_token']);
            header("Location: index.php");
            exit;
        } catch (PDOException $e) {
            $msg = "Database provisioning fault transaction error: " . $e->getMessage();
        }
    } else {
        $msg = "Fadlan xulu milkiilaha saxda ah iyo nooca neefka.";
    }
}
?>
<!DOCTYPE html>
<html lang="so">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Asset Provisioning Center - VetExpert</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    <style>
        .card-custom { border-radius: 16px; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.05); }
    </style>
</head>
<body class="bg-light py-5">

<div class="container" style="max-width: 680px;">
    <div class="card card-custom border-0 bg-white overflow-hidden">
        <div class="card-header bg-dark text-white p-4 border-0">
            <div class="d-flex align-items-center">
                <div class="bg-success p-2 rounded-3 me-3 text-white">
                    <i class="bi bi-plus-circle-fill fs-5"></i>
                </div>
                <div>
                    <h5 class="mb-0 fw-bold">Register New Livestock Asset</h5>
                    <small class="text-muted">Automated secure tracking protocol assignment engine.</small>
                </div>
            </div>
        </div>
        
        <div class="card-body p-4">
            <?php if($msg): ?> 
                <div class="alert alert-danger border-0 shadow-sm rounded-3 mb-4"><i class="bi bi-shield-slash-fill me-2"></i><?= $msg; ?></div> 
            <?php endif; ?>

            <form action="" method="POST" id="regAnimalForm">
                <input type="hidden" name="csrf_token" value="<?= $_SESSION['csrf_token']; ?>">

                <!-- Floating Owner Selector Dropdown -->
                <div class="form-floating mb-3">
                    <select name="owner_id" id="ownerSelect" class="form-select rounded-3" required>
                        <option value="" disabled selected>-- Dooro Milkiilaha Farm-ka --</option>
                        <?php foreach($owners as $owner): ?>
                            <option value="<?= $owner['id']; ?>"><?= htmlspecialchars($owner['name']); ?></option>
                        <?php endforeach; ?>
                    </select>
                    <label for="ownerSelect">Select Account Owner *</label>
                </div>
                
                <div class="row g-3 mb-3">
                    <!-- Floating Species Selector Dropdown -->
                    <div class="col-md-6">
                        <div class="form-floating">
                            <select name="species" id="speciesSelect" class="form-select rounded-3" required>
                                <option value="Bovine (Cow)">Bovine (Cow / Lo')</option>
                                <option value="Ovine (Sheep)">Ovine (Sheep / Ido)</option>
                                <option value="Caprine (Goat)">Caprine (Goat / Ari)</option>
                                <option value="Cameline (Camel)">Cameline (Camel / Geel)</option>
                            </select>
                            <label for="speciesSelect">Biological Species Variant *</label>
                        </div>
                    </div>
                    <!-- Floating Breed Variant Input -->
                    <div class="col-md-6">
                        <div class="form-floating">
                            <input type="text" name="breed" id="breedInput" class="form-control rounded-3" placeholder="Breed" value="Local Breed">
                            <label for="breedInput">Breed Pedigree Variant (Nooca)</label>
                        </div>
                    </div>
                </div>

                <div class="row g-3 mb-4">
                    <!-- Floating Chronological Month Counter Age Input -->
                    <div class="col-md-6">
                        <div class="form-floating">
                            <input type="number" name="age_months" id="ageInput" class="form-control rounded-3" placeholder="Age Months" min="0" value="12">
                            <label for="ageInput">Age Metrics Chronology (Months)</label>
                        </div>
                    </div>
                    <!-- Gender Radio Interface Custom Box -->
                    <div class="col-md-6">
                        <label class="form-label text-muted small d-block mb-2">Gender Identification *</label>
                        <div class="btn-group w-100" role="group">
                            <input type="radio" class="btn-check" name="gender" value="Male" id="genderMale" checked>
                            <label class="btn btn-outline-secondary py-2 border rounded-start" for="genderMale"><i class="bi bi-gender-male me-1"></i> Male</label>

                            <input type="radio" class="btn-check" name="gender" value="Female" id="genderFemale">
                            <label class="btn btn-outline-secondary py-2 border rounded-end" for="genderFemale"><i class="bi bi-gender-female me-1"></i> Female</label>
                        </div>
                    </div>
                </div>

                <div class="d-flex justify-content-between border-top pt-4">
                    <a href="index.php" class="btn btn-light border rounded-pill px-4 py-2">Hada Ka Noqo</a>
                    <button type="submit" id="subBtn" class="btn btn-success rounded-pill px-5 py-2 fw-bold shadow-sm">
                        <span id="btnText"><i class="bi bi-hdd-network-fill me-2"></i>Provision Asset</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    document.getElementById('regAnimalForm').addEventListener('submit', function() {
        document.getElementById('subBtn').disabled = true;
        document.getElementById('btnText').textContent = "Registering onto secure ledger network...";
    });
</script>
</body>
</html>